print("解一元二次方程式:")
print("請輸入 a 值")
print("請輸入 b 值")
print("請輸入 c 值")
a = int(input("a: "))
b = int(input("b: "))
c = int(input("c: "))
d =(b**2) - (4*a*c)
x = (-b-d**0.5)/(2*a)
y = (-b+d**0.5)/(2*a)
print('一元二次方程式的解:',x,y)